### PR TITLE
Re-organize code to maintain easy

### PR DESCRIPTION
**Pull request by amarin**
Hi,I've found some issues in code, but stopped on it is not well organized yet.

So I've split types into separated files and fix some comments first. 
Please consider apply my merge-request.

### CODE REVIEW

**Review by berryhe — APPROVED** [review]

**Comment by srwiley** [comment]
Sorry this took so long to get to, Aleksey. I was busy with some other matters. Just a couple of comments:

1) What is the a_doc.go file doing there? Is there any reason to keep this as it is empty?

2) I never put much effort into differentiating between public and private methods. Generally I err on the side of making a lot 
of things public, and let the users decide which they want to call. So, some methods in the pubic.go file may not be entirely appropriate, although in general I do not see the harm.

Thanks for your help!

**Comment by srwiley** [comment]
Also, Aleksey, I had to merge this in the command line due to some conflicts. Unfortunately because of this you are not listed as a contributor. As far as I can tell, there is no way to do this manually, so if you want to be listed please make another pull request and I will try to merge it directly.

**Comment by amarin** [comment]
It's ok. Seems it happened because of some changes were made after commit from which I forked from and pull request became incompatible a little. In that case next time feel free to ask me to pull last changes to made merge fully compatible.

As for a_doc.go file, I've want to fill it with documentation, but lost this intention somewhere.

No promise I'll be back soon, cause busy on different project right now, but going to use oksvg in future.
Thanks for you work!

**Comment by srwiley** [comment]
Please provide a pull request when you want to make the a_doc.go file useful. For now I will take it out and retain all document information in the /doc folder, where the all the other docs reside.

**Pull request merged**
