### PR TITLE
support image element

### PR DESCRIPTION
**Pull request by xushiwei**

### CODE REVIEW

**Comment by xushiwei** [comment]
[svg-with-images.zip](https://github.com/srwiley/oksvg/files/4459252/svg-with-images.zip)

**Comment by srwiley** [comment]
Thank you xushiwei. I have merged your additions into the imageElt branch for testing and evaluation. If it looks good I will merge it into the master branch in a few days.

**Comment by srwiley** [comment]
Xushiwei: I am having trouble getting any examples of the image element to run. The problem seems to be the URL. Could you please provide an example svg using the image element so that we can incorporate it into the tests? 
Thank you in advance,
srwiley

**Comment by xushiwei** [comment]
https://github.com/srwiley/oksvg/files/4459252/svg-with-images.zip @srwiley

**Pull request merged**
