### PR TITLE
Defs support

### PR DESCRIPTION
**Pull request by Noofbiz**
This is a work in progress. All I've done so far is moved the drawing for each element to a map, so that down the road when the defs and use tags are implemented the use tag can call the draw functions from the map too, rather than reimplement each one.

Fixes #11

### CODE REVIEW

**Comment by srwiley** [comment]
OK, let me know when you have it working and tests to prove it.

**Comment by Noofbiz** [comment]
Tests now pass, same as before. I'm a little confused about the "fill_i.png"s though, I thought something was wrong with what I did, but they're all blank on master as well for me.

I still need to add support for "use" so the defs can actually be used, and then I'll make some svgs that use defs/use and add them to the tests. Then I should be ready for review!

**Comment by Noofbiz** [comment]
Alright, it's ready for review. Not sure why, but the button to switch from draft to actual PR is missing on my end.

**Comment by srwiley** [comment]
I have to think about some of these changes and also confirm the testing and benchmarking. I will get back to you soon...

**Comment by srwiley** [comment]
This looks very well done Noofbiz. It is like you are completing my thoughts! Great job!

For now I am going to place it in a separate branch, "defs", and let some people test it if they want. They are some of the more serious oksvg users I know of. So, @andydotxyz,  @ajstarks, @rcoreilly, and anyone else, if you want, then please try the defs branch of oksvg. If no problems are reported after a couple of weeks I will merge defs into the main branch.

**Comment by andydotxyz** [comment]
In my testing it appears to break the loading the background gradient in this file:
https://github.com/fyne-io/examples/blob/develop/solitaire/faces/back.svg

**Comment by Noofbiz** [comment]
It's probably not calling the gradient since it's saved as a def now but never actually executed. I'll look into it when I can. The solution is probably to make gradients a special case and execute them immediately after being stored in the defs

**Comment by srwiley** [comment]
Maybe gradients and defs should be stored separately? Then there would be
no need for the map's value to have and interface{} type. Also, I would
like to at some point I would like to define the drawFuncs like this:

var (
    svgF svgFunc = func(c *IconCursor, attrs []xml.Attr) error {
        c.icon.ViewBox.X = 0
        c.icon.ViewBox.Y = 0
        c.icon.ViewBox.W = 0
        c.icon.ViewBox.H = 0
        var width, height float64
        var err error
        for _, attr := range attrs {
            switch attr.Name.Local {
            case "viewBox":
                err = c.GetPoints(attr.Value)
                if len(c.points) != 4 {
                    return errParamMismatch
                }
                c.icon.ViewBox.X = c.points[0]
                c.icon.ViewBox.Y = c.points[1]
                c.icon.ViewBox.W = c.points[2]
                c.icon.ViewBox.H = c.points[3]
            case "width":
                wn := trimSuffixes(attr.Value)
                width, err = strconv.ParseFloat(wn, 64)
            case "height":
                hn := trimSuffixes(attr.Value)
                height, err = strconv.ParseFloat(hn, 64)
            }
            if err != nil {
                return err
            }
            if c.icon.ViewBox.W == 0 {
                c.icon.ViewBox.W = width
            }
            if c.icon.ViewBox.H == 0 {
                c.icon.ViewBox.H = height
            }
        }
        return nil
    }
    drawFuncs = map[string]svgFunc{
        "svg": svgF,
    }
)

For course I only did it for one function. But it avoids having to populate
the drawFuncs map using the init() function.
I doubt it is much of a performance enhancer, but it is a little cleaner
syntactically IMHO.
Not a huge deal. Either you can do it, or I can after we merge your pull
request into the master, once we get deal with the grad issue.

**Comment by srwiley** [comment]
Figured out how to merge into a separate branch on github. Will delete other 'defs' branch

**Pull request merged**
